dist: xenial
language: python
addons:
  firefox: latest
services:
  - xvfb
python:
  - "3.7.4"
before_install:
  - pip install poetry
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - sudo tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C /usr/bin
  - sudo chmod a+x /usr/bin/geckodriver
  - openssl aes-256-cbc -K $encrypted_f8d7365fdf21_key -iv $encrypted_f8d7365fdf21_iv -in deploy_id_rsa.enc -out deploy_id_rsa -d
install:
  - poetry install
script:
  - poetry run pytest
deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: script
  script: poetry run fab -i deploy_id_rsa deploy
