dist: xenial
language: python
addons:
  firefox: latest
python:
  - "3.7.4"
before_install:
  - pip install poetry
  - sudo apt-get install xvfb
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
  - sudo tar -xzf geckodriver-v0.19.0-linux64.tar.gz -C /usr/bin
  - sudo chmod a+x /usr/bin/geckodriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 # give xvfb some time to start
install:
  - poetry install
script:
  - poetry run pytest
