dist: xenial
language: python
addons:
  firefox: latest
services:
  - xvfb
python:
  - "3.7.4"
before_install:
  - pip install poetry
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - sudo tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C /usr/bin
  - sudo chmod a+x /usr/bin/geckodriver
install:
  - poetry install
script:
  - poetry run pytest
