version: '3'

services:
  django:
    image: docker.pkg.github.com/khazidhea/loans/latest
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn -c gunicorn.conf core.wsgi"
    volumes:
      - ./gunicorn.conf:/src/gunicorn.conf
      - ./logs:/logs
      - ./static:/src/staticfiles
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    depends_on:
      - django
    environment:
      - TZ=Asia/Almaty
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/logs
      - ./static:/static
    ports:
      - "80:80"
      - "443:443"
