# Generated by Django 2.2.5 on 2019-10-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('active', 'active'), ('paid', 'paid'), ('expired', 'expired')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='term',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='term_counter',
            field=models.IntegerField(default=1),
        ),
    ]
